### ISSUE TITLE
install tutorial not good

### ISSUE THREAD

**Issue by pizzav-xyz** [Swagguy47/BigCityCustomKitties#2]
it says to install it but it just brings you to a page with download sourcecode and doesnt tell you how to do it

**Comment by pizzav-xyz** [comment]
the bepinex part

**Comment by LeviBroadnax** [comment]
hey @kittenvr 👋
Pull request https://github.com/Swagguy47/BigCityCustomKitties/pull/3 should resolve this.

If the PR can't be merged for whatever reason, these are the updated instructions:

### Installation:

1. Locate your game folder containing the game's executable `Little Kitty, Big City.exe`.
   - This is where you will extract the contents of the following zips.
2. Extract the contents of [BepInEx_win_x64_5.4.23.2.zip](https://github.com/BepInEx/BepInEx/releases/download/v5.4.23.2/BepInEx_win_x64_5.4.23.2.zip) to your game folder. 
3. Extract the contents of [BCCustomKitties_v1.2.0.zip](https://github.com/Swagguy47/BigCityCustomKitties/releases/download/v.1.2.0/BCCustomKitties_v1.2.0.zip) to your game folder. 
4. Test that the installation worked by:
     - Renaming `/LittleKittyBigCity/Skins/Current.png` to `default.png`
     - Moving `/Skins/extras/Vet.png` to `/Skins/Current.png`
     - After loading into the game, the cat should be orange

If that doesn't work, here's a script that does the same thing:
https://gist.github.com/SystemStack/102e998ab0c6d1037c371d5cba8ab0ce

Tell me if I helped!
